version: '3.5'

services:

  db:
    build: ./database
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: trigun117/wikipedia-telegram-bot
    environment:
      TOKEN: 
      HOST: db
      PORT: 5432
      USER: 
      PASSWORD: 
      DBNAME: 
      SSLMODE: 
